### ISSUE TITLE
Requesting openjdk9 extension being updated to 21.08

### ISSUE THREAD

**Issue by nbenitez** [flathub/org.freedesktop.Sdk.Extension.openjdk#10]
I'm filing this issue here because issue tracker for openjdk9 is currently read-only.

I'm packaging this PDF app for Flathub:\
http://pdfpresenter.sourceforge.net/

This app is abandonware, the last release was in 2011, but it's useful PDF Presentation software, I set the flatpak to not have network access and filesystem access is also limited, so we don't have to worry about security wrt using an old java version like openjdk9.

**Why this app needs Java 9?**
Because starting with Java 10 the classes `com.sun.java.swing.plaf.windows` were removed, which PDFPresenter uses. ([info](https://stackoverflow.com/q/53437209))

**Why don't you use openjdk8 which is currently available for latest 21.08?**
Because Java 8 lacks `GDK_SCALE` support, that means app interface looks tiny in HiDPI monitors which are more prevalent these days. `GDK_SCALE` support was implemented in Java starting with version 9 ([info](https://openjdk.java.net/jeps/263)).

**But Openjdk9 is available in flathub for runtime 18.08, why don't you use that?**
Yeah, that would be my last resort, that's what I'm using right now and the app runs fine with good HiDPI support. But it'll be generally good to use an updated runtime like 21.08. I also don't know if I will encounter a problem when submitting the app to flathub with an EOL runtime like 18.08

Thanks for your work in Flathub,

**Comment by mbooth101** [comment]
The source is available, why not patch the application to work on an actually supported JDK?

```com.sun.java.swing.plaf.windows``` --> ```javax.swing.plaf.basic```

**Comment by hfiguiere** [comment]
This is kinda against the Flathub policy to do that kind of changes. The goal being to reduce the maintenance burden.

**Comment by mbooth101** [comment]
> This is kinda against the Flathub policy to do that kind of changes. The goal being to reduce the maintenance burden.

[Citation Needed] ;-)

Lots of applications in Flathub contain patches. IMO it's even worse to depend on EOL and unmaintained runtimes.

**Comment by hfiguiere** [comment]
Here is the citation:

https://github.com/flathub/flathub/wiki/App-Maintenance#strongly-discouraged

> Patches which add (or remove) application functionality do not belong in the Flathub repository. The application on Flathub should reflect, as closely as possible, the application in its unadulterated form, direct from its authors.

**Comment by Erick555** [comment]
This is about patching abandoned app in order to work with supported java version. I think it's similar to patching something to work with gcc 11 instead of asking to provide gcc 8 somewhere.

**Comment by mbooth101** [comment]
@Erick555 Agreed, such a patch would not be adding or removing any functionality.

**Comment by nbenitez** [comment]
> The source is available, why not patch the application to work on an actually supported JDK?
> 
> `com.sun.java.swing.plaf.windows` --> `javax.swing.plaf.basic`

Because it's not trivial, it's a decent amount of work, I looked into it. Thanks anyway, I'll submit with 18.08 and see what happens.

**Comment by hfiguiere** [comment]
18.08 is EOL, so it's unlikely to pass the test.

**Comment by hfiguiere** [comment]
> This is about patching abandoned app in order to work with supported java version. I think it's similar to patching something to work with gcc 11 instead of asking to provide gcc 8 somewhere.

Quite not, from my understanding. It's like patching to build on Qt6 when it only support Qt5.0.

**Comment by Erick555** [comment]
Maybe app could just bundle old java?

**Comment by nbenitez** [comment]
> Maybe app could just bundle old java?

Not possible because the json references some files needed for the build like:
https://fedorapeople.org/~mbooth/bootstrap_jdk/bootstrap-openjdk-9.0.4.11-6.fc28.x86_64.tar.bz2

which are not longer available.

**Comment by Erick555** [comment]
I think this is just part of flathub maintainer secret sauce to build java. You don't have to rely on it.

**Comment by tsmock** [comment]
Since source for pdfpresenter is available, the solution is to fork it and update it. Updating an EOL runtime is unwise, as far as I'm concerned.

svn source: https://sourceforge.net/p/pdfpresenter/code/HEAD/tree/

If you decide to move it to git, you can use either `git-svn` or `reposurgeon`.
