### ISSUE TITLE
Can I use this to install openjdk system-wide?

### ISSUE THREAD

**Issue by K0-RR** [flathub/org.freedesktop.Sdk.Extension.openjdk#11]
I'm on Fedora 35 Silverblue and wanted to install Java 18 (or 17 as it looks time this repository is outdated?) but all I see is some info for developers. I just want to manage Java from flatpak like my other apps.

**Comment by mbooth101** [comment]
In general, no. This is a SDK extension, not an end user application.

In Flathub, Java is considered a language runtime for other Java applications -- it is not by itself, an application. The intention is that application maintainers use this SDK extension to build and/or ship their Java application in Flathub.

On Fedora Silverblue, you should probably be using the standard rpm-ostree way of installing Java, e.g:

    $ rpm-ostree install java-latest-openjdk # JRE
    $ rpm-ostree install java-latest-openjdk-devel # JDK
