### ISSUE TITLE
Update to 22.08

### ISSUE THREAD

**Issue by razzeee** [flathub/org.freedesktop.Sdk.Extension.openjdk#14]
As the new freedesktop is out now, it would be nice, to be able to build stuff based on 22.08 with openjdk

**Comment by dogtopus** [comment]
Did some experiment on openjdk17 and found an alias collision problem with cacerts generation. Had to use a workaround that adds part of the fingerprint as suffix to the alias when needed.

```
Adding AE:C5:FB:3F:C8:E1:BF:C4:E5:4F:03:07:5A:9A:E8:00:B7:F7:B6:FA (autoridaddecertificacionfirmaprofesionalcifa62634068)
keytool error: java.lang.Exception: Certificate not imported, alias <autoridaddecertificacionfirmaprofesionalcifa62634068> already exists
Error: module cacerts: Child process exited with code 1
```

Other than that it seems to build fine under SDK 22.08.

**Comment by razzeee** [comment]
Do you think the fix is different from https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/pull/15

**Comment by dogtopus** [comment]
@razzeee Instead of omitting these certificates, I added them with a suffix derived from their fingerprints. Something like

```diff
diff --git a/extract_cacerts.sh b/extract_cacerts.sh
index 9be2b9d..42afcf7 100755
--- a/extract_cacerts.sh
+++ b/extract_cacerts.sh
@@ -35,6 +35,10 @@ for certificate in $(ls /etc/ssl/certs/*.pem) ; do
        issuer=$(echo "$cert" | grep '^Issuer' | cut -d' ' -f1 --complement)
        fprint=$(echo "$cert" | grep 'SHA1:' | cut -d' ' -f3)
        alias=$(get_alias "$issuer")
+       $jdk/bin/keytool -list -noprompt -alias $alias -storepass changeit -storetype JKS -keystore cacerts &>/dev/null
+       if [[ $? -eq 0 ]]; then
+           alias="${alias}-$(echo "${fprint}" | cut -f 1-8 -d ':' | tr -d ':')"
+       fi
        echo "Adding $fprint ($alias)"
        $jdk/bin/keytool -importcert -noprompt -alias $alias -storepass changeit -storetype JKS -keystore cacerts -file $certificate
 done
```

**Comment by razzeee** [comment]
Wouldn't that add them twice?

**Comment by dogtopus** [comment]
They have different fingerprints. Probably certificates that got revoked early or something. I'm not sure why it's like that so I still included them.

**Comment by razzeee** [comment]
If that's the case, maybe it should be fixed in the platform

dogtopus ***@***.***> schrieb am So., 16. Okt. 2022, 07:00:

**Comment by razzeee** [comment]
I'll close this, as https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk17/tree/branch/22.08 has been updated and it's probably a better idea to use it as it's pinned to openjdk17

**Comment by teohhanhui** [comment]
The whole point of this package is so that we (end users) can use the latest openjdk version, no?

From the README:

> This is not a long-term support (LTS) version and will be periodically updated as new JDKs are released.

You should deprecate this package if the recommendation is instead to have it pinned to a specific version.

**Comment by razzeee** [comment]
Not sure how this is an end user decission, it would be a packager/dev decission and as the app I'm packaging in likely breaking, if you just switch jdk major versions, it's not a good idea to use this for that project. It might be different for other maintainers.

**Comment by dogtopus** [comment]
Just curious: Is this package deprecated?

**Comment by teohhanhui** [comment]
> Not sure how this is an end user decission

For example, when I need openjdk in vscode, or I need to run a Java program by `flatpak run` directly with the `org.freedesktop.Sdk` runtime.

**Comment by razzeee** [comment]
> Just curious: Is this package deprecated?

That's a question for the maintainers and probably worth it's own issue.
