### ISSUE TITLE
Support for 19.08

### ISSUE THREAD

**Issue by taaem** [flathub/org.freedesktop.Sdk.Extension.openjdk#2]
Hello,
it would be nice to have support for the latest openJDK for 19.08 Sdk, which currently doesn't have this extension and thus breaks apps, that updated to 19.08 but rely on the extension.
Best Regards

**Comment by TingPing** [comment]
Branch made lets see if it builds: https://flathub.org/builds/#/builders/32/builds/8859

EDIT: Oh it has to be done to openjdk11 first.

**Comment by mbooth101** [comment]
Hi, sorry for the delay, I will look into it this week.

**Comment by mbooth101** [comment]
Fixed in 40b402e157033d8ad573002b08cdc35d9a65e6ca -- a build should be available in flathub now or very soon.
