### ISSUE TITLE
Updated to OpenJDK 14

### ISSUE THREAD

**Issue by overheadhunter** [flathub/org.freedesktop.Sdk.Extension.openjdk#3]
JDK 14 is now available.

One important feature is its preview of `jpackage` allowing to bundle stripped-down JREs with self-contained application bundles, which I believe is relevant for building Flatpaks.

**Comment by x80486** [comment]
~Just posting another comment to raise the interest for this one~ ...I was looking at the documentation, not the repo content; it's already on version `14` :roll_eyes:

**Comment by mbooth101** [comment]
D'oh I fixed the readme file, thanks for pointing it out
