### ISSUE TITLE
OpenJDK 21 is now LTS by Oracle

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/org.freedesktop.Sdk.Extension.openjdk#38]
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Would it thus be wise to create a new LTS repository?

**Comment by tsmock** [comment]
If someone else wants to fork this repo to make a new LTS repository, I'm perfectly fine with that. _I'm_ currently disinclined to do so -- I don't feel like I would have enough time to maintain it.

It _should_ be fairly low maintenance -- I just have to update the Java major version every six months or so. Everything else is done via automation.

**Comment by Doomsdayrs** [comment]
Alright, I'll toss together a new repo soon

**Comment by der-eismann** [comment]
Any updates on this? I guess apps want to use Java 21, but don't want to use the unversioned `latest` repo this is atm. So it would be great to have an LTS java21 repo here as well :slightly_smiling_face:

**Comment by Zishan-Rahman** [comment]
I just set up [a new PR on flathub/flathub](https://github.com/flathub/flathub/pull/4814) to try and get a Java 21 LTS Flatpak added to Flathub. I let @Doomsdayrs (sorry for the ping) know, over email, about my intentions to set it up, and they're happy for me to do so.

**Comment by Zishan-Rahman** [comment]
[The Java 21 LTS Flatpak has now been added to Flathub](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk21/). This issue can be closed now :+1:
