### ISSUE TITLE
Openjdk 8 extension actually installs openjdk 14

### ISSUE THREAD

**Issue by casept** [flathub/org.freedesktop.Sdk.Extension.openjdk#4]
I'm trying to package a minecraft launcher (work so far: https://github.com/casept/LauncherV3/tree/flatpak). Minecraft is very sensitive to the Java version, so it's important that the JRE version is exactly 8. However, both the in-app java selector menu and `java --version` in a debug shell in the flatpak report the version as openJDK 14. Is this a bug, or am I misunderstanding something?

**Comment by mbooth101** [comment]
This is not OpenJDK 8, I don't know where you got that impression. *THIS* repository, where you filed *THIS* bug, is for the OpenJDK 14 extension. See the readme file:

https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/blob/branch/19.08/README.md

So I'm not sure what you expected, but if this is the wrong OpenJDK for you, then don't use it ;-)

For reference the following other OpenJDK extensions exist:

* OpenJDK 11: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11
* OpenJDK 8: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8

**Comment by mbooth101** [comment]
I took a look at your flatpak manifest and I'm surprised it builds at all because you require the OpenJDK 8 extension, but then call the OpenJDK 14 installation script!

I guess you must have both extensions installed on your build machine -- but this would **definitely** cause the build to fail at Flathub.

**Comment by casept** [comment]
Sorry for using the wrong issue tracker, my bad!
