### ISSUE TITLE
Update to OpenJDK 16

### ISSUE THREAD

**Issue by KhalilSantana** [flathub/org.freedesktop.Sdk.Extension.openjdk#6]
OpenJDK 16 hit general-availability: https://jdk.java.net/16/

As such, I believe this flatpak bundle is outdated, or will this update land elsewhere?

Thanks!

**Comment by mbooth101** [comment]
Updated to 16.0.1 in 29ee5f31e2164f86524c8aaee4f8ef9207d42c97
